import type { Metadata } from "next";
import { Providers } from "./providers";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import {Navbar} from "@/app/ui/component/Navigation/NavBar/Navbar";
import Navigation from "./ui/component/Navigation/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navigation />
          {children}
        </Providers>
      </body>
    </html>
  );
}
